### ISSUE TITLE
https, cors 과제

### ISSUE THREAD

**Issue by kihyunnn** [likelion-Inha-12/kihyunnn#11]
![KakaoTalk_20240522_030939649](https://github.com/likelion-Inha-12/kihyunnn/assets/142724910/7b337a47-0c44-4044-8377-65e65d34957a)

키워드 과제 : https://kihyunnnnn.tistory.com/5

**Comment by juwon0403** [comment]
앞으로 어떻게 적용하면 좋을지에 대해 생각해보는 자세 아주 좋습니당
깔끔한 정리 최고!-!

+) 주황색 박스를 찾다보면, 출처 설명하는 부분에 2개가 더 숨어있을 거야! 요것도 마저 찾아서 정리해주면 될 둣
+) 운영진들의 노고를 이렇게나 깊이 헤아려주다니.. 13기 운영진의 자질을 갖추고 있는 아기사자구나^^ ㅋㅋ 근데 진짜 감동이야ㅠㅠ

**Comment by kihyunnn** [comment]
헉 왠지 할게 적더라니.. 내가 빼먹었군.. 티스토리에 수정 완료했슴당
진짜 세션 자료 퀄리티 쵝오에요. 세션끝나도 공부 할 때 끝까지 우려먹으면서 써야지~~

**Comment by juwon0403** [comment]
유튜브 예시까지 아주 굿입니당bb
덕분에 노래 들으면서 체크 완. ㅎㅎ
