### ISSUE TITLE
배포 과제 완료

### ISSUE THREAD

**Issue by kihyunnn** [likelion-Inha-12/kihyunnn#9]
![image](https://github.com/likelion-Inha-12/kihyunnn/assets/142724910/c5a7e628-9077-43e2-a1c5-2189e31a8392)
![image](https://github.com/likelion-Inha-12/kihyunnn/assets/142724910/d08b7ec9-5b2a-41e2-b540-5cc7792aed0f)

접속은 잘 되는데 맨 처음 로켓 페이지로는 안뜹니당

**Comment by juwon0403** [comment]
내 프로젝트에서는 url 지정이 안 되어 있어서 로켓 모양이 떴던 거더라고,,^^
결론적으로 404 뜨는 게 맞슴다

수고했우~~
